FROM python:3.9-bullseye

ENV VIRTUAL_ENV=/opt/venv
RUN python -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY requirements.txt requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

RUN apt-get update
RUN apt-get install -y ocrmypdf

RUN mkdir /app
RUN mkdir /app/src
RUN mkdir /data
WORKDIR /app

COPY ./src ./src

WORKDIR /app/src

COPY docker-compose.yml .

ENV FLASK_APP app.py

CMD gunicorn -k uvicorn.workers.UvicornWorker app:app --bind 0.0.0.0:5050

